# Проведение EDA

In [34]:
import pandas as pd

df = pd.read_csv("data/olympiad_results.csv")
print(df.shape)
df.head(3)

(8037, 46)

,student_id,region,school_number,grade,start_time,end_time,Task_1_answer,Task_1_correct,Task_1_time_spent,Task_2_answer,Task_2_correct,Task_2_time_spent,Task_3_answer,Task_3_correct,Task_3_time_spent,Task_4_answer,Task_4_correct,Task_4_time_spent,Task_5_answer,Task_5_correct,Task_5_time_spent,Task_6_answer,Task_6_correct,Task_6_time_spent,Task_7_answer,Task_7_correct,Task_7_time_spent,Task_8_answer,Task_8_correct,Task_8_time_spent,Task_9_answer,Task_9_correct,Task_9_time_spent,Task_10_answer,Task_10_correct,Task_10_time_spent,Task_11_answer,Task_11_correct,Task_11_time_spent,Task_12_answer,Task_12_correct,Task_12_time_spent,total_score,device_type,attempts_count,disconnects
0,S200000,Краснодар,9,11,2026-04-10 11:10:00,2026-04-10 11:25:19,4.0,0.0,93.0,1.0,0.0,75.0,2.0,0.0,65.0,1.0,0.0,81.0,1.0,0.0,66.0,1.0,0.0,47.0,2.0,0.0,109.0,3.0,1.0,30.0,3.0,1.0,59.0,1.0,1.0,86.0,2.0,0.0,84.0,4.0,0.0,124.0,3,desktop,2,0
1,S200001,Ростов-на-Дону,44,9,2026-04-10 10:30:00,2026-04-10 10:44:19,3.0,0.0,105.0,2.0,0.0,71.0,2.0,0.0,59.0,1.0,1.0,117.0,3.0,0.0,59.0,3.0,1.0,60.0,4.0,1.0,67.0,1.0,1.0,76.0,1.0,0.0,33.0,2.0,1.0,76.0,4.0,1.0,73.0,4.0,0.0,63.0,6,mobile,2,0
2,S200002,Екатеринбург,44,9,2026-04-10 10:25:00,2026-04-10 10:38:33,4.0,1.0,60.0,3.0,0.0,98.0,2.0,0.0,67.0,1.0,1.0,26.0,3.0,0.0,86.0,3.0,1.0,81.0,4.0,1.0,84.0,2.0,1.0,71.0,1.0,0.0,62.0,NaN,NaN,NaN,1.0,1.0,101.0,1.0,1.0,77.0,7,mobile,1,1

In [35]:
print("Пропуски:")
print(df.isnull().sum())
print(f"Общее количество пропусков: {df.isnull().sum().sum()}")

Пропуски:
student_id              0
region                  0
school_number           0
grade                   0
start_time              0
end_time                0
Task_1_answer         318
Task_1_correct        318
Task_1_time_spent     318
Task_2_answer         341
Task_2_correct        341
Task_2_time_spent     341
Task_3_answer         315
Task_3_correct        315
Task_3_time_spent     315
Task_4_answer         310
Task_4_correct        310
Task_4_time_spent     310
Task_5_answer         299
Task_5_correct        299
Task_5_time_spent     299
Task_6_answer         327
Task_6_correct        327
Task_6_time_spent     327
Task_7_answer         312
Task_7_correct        312
Task_7_time_spent     312
Task_8_answer         316
Task_8_correct        316
Task_8_time_spent     316
Task_9_answer         313
Task_9_correct        313
Task_9_time_spent     313
Task_10_answer        316
Task_10_correct       316
Task_10_time_spent    316
Task_11_answer        287
Task_11_correct       287
Task_11_time_spent    287
Task_12_answer        321
Task_12_correct       321
Task_12_time_spent    321
total_score             0
device_type             0
attempts_count          0
disconnects             0
dtype: int64
Общее количество пропусков: 11325

Всего оказалось 11325 пропусков, требующих дальнейшей обработки

In [36]:
df.dtypes #посмотрим типы данных

student_id             object
region                 object
school_number           int64
grade                   int64
start_time             object
end_time               object
Task_1_answer         float64
Task_1_correct        float64
Task_1_time_spent     float64
Task_2_answer         float64
Task_2_correct        float64
Task_2_time_spent     float64
Task_3_answer         float64
Task_3_correct        float64
Task_3_time_spent     float64
Task_4_answer         float64
Task_4_correct        float64
Task_4_time_spent     float64
Task_5_answer         float64
Task_5_correct        float64
Task_5_time_spent     float64
Task_6_answer         float64
Task_6_correct        float64
Task_6_time_spent     float64
Task_7_answer         float64
Task_7_correct        float64
Task_7_time_spent     float64
Task_8_answer         float64
Task_8_correct        float64
Task_8_time_spent     float64
Task_9_answer         float64
Task_9_correct        float64
Task_9_time_spent     float64
Task_10_answer        float64
Task_10_correct       float64
Task_10_time_spent    float64
Task_11_answer        float64
Task_11_correct       float64
Task_11_time_spent    float64
Task_12_answer        float64
Task_12_correct       float64
Task_12_time_spent    float64
total_score             int64
device_type            object
attempts_count          int64
disconnects             int64
dtype: object

In [37]:
data_dict = pd.read_csv("data/olympiad_data_dictionary.csv")
print(data_dict)

              Столбец                                           Описание
0          student_id                   Уникальный идентификатор ученика
1              region  Регион школы ученика (содержит опечатки и разн...
2       school_number                         Номер школы внутри региона
3               grade                               Класс ученика (5-11)
4          start_time                 Время начала прохождения олимпиады
5            end_time              Время окончания прохождения олимпиады
6       Task_N_answer        Выбранный вариант ответа на задание N (1-4)
7      Task_N_correct  Признак правильности ответа на задание N (1 - ...
8   Task_N_time_spent        Время, затраченное на задание N, в секундах
9         total_score  Итоговый балл за олимпиаду (в части строк тип ...
10        device_type  Тип устройства прохождения (desktop/mobile/tab...
11     attempts_count                  Количество попыток входа в сессию
12        disconnects  Количество разрывов соединения во время прохож...

In [38]:
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 200)

df.head(10)
df.sample(10, random_state=42)

,student_id,region,school_number,grade,start_time,end_time,Task_1_answer,Task_1_correct,Task_1_time_spent,Task_2_answer,Task_2_correct,Task_2_time_spent,Task_3_answer,Task_3_correct,Task_3_time_spent,Task_4_answer,Task_4_correct,Task_4_time_spent,Task_5_answer,Task_5_correct,Task_5_time_spent,Task_6_answer,Task_6_correct,Task_6_time_spent,Task_7_answer,Task_7_correct,Task_7_time_spent,Task_8_answer,Task_8_correct,Task_8_time_spent,Task_9_answer,Task_9_correct,Task_9_time_spent,Task_10_answer,Task_10_correct,Task_10_time_spent,Task_11_answer,Task_11_correct,Task_11_time_spent,Task_12_answer,Task_12_correct,Task_12_time_spent,total_score,device_type,attempts_count,disconnects
6638,S206610,Уфа,37,6,2026-04-10 10:15:00,2026-04-10 10:30:02,2.0,0.0,71.0,3.0,0.0,111.0,4.0,0.0,74.0,4.0,1.0,51.0,1.0,0.0,78.0,2.0,0.0,76.0,3.0,1.0,104.0,4.0,0.0,85.0,3.0,0.0,46.0,2.0,1.0,62.0,3.0,0.0,79.0,2.0,1.0,65.0,4,desktop,1,1
6633,S206605,Уфа,43,5,2026-04-10 09:22:00,2026-04-10 09:34:05,3.0,0.0,104.0,1.0,0.0,72.0,3.0,0.0,59.0,3.0,0.0,82.0,2.0,0.0,55.0,NaN,NaN,NaN,1.0,0.0,58.0,1.0,0.0,74.0,2.0,1.0,42.0,3.0,0.0,79.0,1.0,0.0,49.0,3.0,0.0,51.0,1,desktop,1,0
7328,S207297,Пермь,22,5,2026-04-10 11:13:00,2026-04-10 11:23:24,2.0,0.0,38.0,2.0,1.0,29.0,NaN,NaN,NaN,1.0,0.0,50.0,1.0,0.0,138.0,1.0,1.0,47.0,2.0,0.0,43.0,NaN,NaN,NaN,1.0,0.0,21.0,2.0,0.0,84.0,1.0,1.0,97.0,1.0,1.0,77.0,4,desktop,1,0
730,S200728,Казань,50,9,2026-04-10 10:47:00,2026-04-10 11:00:34,4.0,1.0,35.0,4.0,0.0,87.0,1.0,1.0,74.0,2.0,1.0,70.0,3.0,1.0,94.0,3.0,0.0,40.0,4.0,1.0,43.0,4.0,0.0,51.0,2.0,0.0,83.0,4.0,1.0,74.0,3.0,0.0,84.0,4.0,0.0,79.0,6,desktop,2,0
1515,S201506,Екатеринбург,7,8,2026-04-10 11:24:00,2026-04-10 11:39:19,1.0,0.0,49.0,1.0,0.0,83.0,1.0,0.0,59.0,1.0,1.0,90.0,4.0,0.0,82.0,1.0,0.0,69.0,3.0,0.0,80.0,2.0,1.0,82.0,1.0,0.0,80.0,4.0,0.0,90.0,3.0,0.0,82.0,2.0,0.0,73.0,2,desktop,2,0
239,S200238,Новосибирск,37,10,2026-04-10 09:39:00,2026-04-10 09:52:57,1.0,1.0,108.0,2.0,1.0,62.0,4.0,1.0,35.0,4.0,1.0,95.0,1.0,1.0,64.0,4.0,0.0,39.0,3.0,1.0,13.0,1.0,1.0,88.0,1.0,1.0,69.0,2.0,1.0,100.0,2.0,1.0,61.0,3.0,1.0,103.0,11,desktop,1,0
2603,S202589,Ростов-на-Дону,22,5,2026-04-10 11:23:00,2026-04-10 11:35:40,3.0,0.0,61.0,4.0,0.0,70.0,1.0,1.0,47.0,2.0,1.0,31.0,3.0,1.0,78.0,2.0,0.0,51.0,2.0,0.0,56.0,1.0,0.0,105.0,1.0,0.0,36.0,1.0,0.0,91.0,3.0,0.0,42.0,1.0,0.0,92.0,3,desktop,2,0
5857,S205830,Новосибирск,36,10,2026-04-10 11:02:00,2026-04-10 11:14:58,1.0,1.0,81.0,2.0,0.0,5.0,1.0,1.0,34.0,3.0,1.0,77.0,1.0,1.0,98.0,1.0,1.0,116.0,2.0,1.0,74.0,1.0,1.0,38.0,3.0,1.0,73.0,3.0,1.0,68.0,2.0,1.0,60.0,2.0,1.0,54.0,11,mobile,2,0
4574,S204551,Воронеж,5,9,2026-04-10 11:30:00,2026-04-10 11:46:24,2.0,0.0,86.0,4.0,0.0,114.0,1.0,0.0,83.0,1.0,0.0,62.0,4.0,1.0,66.0,1.0,1.0,103.0,1.0,1.0,65.0,2.0,0.0,75.0,4.0,0.0,67.0,3.0,0.0,85.0,2.0,0.0,76.0,1.0,1.0,102.0,4,mobile,1,0
5487,S205462,Москва,49,9,2026-04-10 10:11:00,2026-04-10 10:22:39,2.0,0.0,97.0,2.0,0.0,51.0,NaN,NaN,NaN,2.0,0.0,71.0,4.0,1.0,89.0,4.0,1.0,27.0,4.0,0.0,80.0,1.0,1.0,82.0,3.0,0.0,72.0,2.0,0.0,26.0,4.0,1.0,53.0,1.0,1.0,51.0,5,desktop,2,0

Посмотрели полную таблицу (10 рандомных примеров), а также проверим датасет на полные дубли

In [39]:
print("Полные дубликаты:", df.duplicated().sum())
print("Дубликаты по student_id:", df.duplicated(subset=['student_id']).sum())

Полные дубликаты: 37
Дубликаты по student_id: 37

Получили 37 дублей, удалим их

In [40]:
df = df.drop_duplicates()
print("Полные дубликаты:", df.duplicated().sum())

Полные дубликаты: 0

Здесь видно первые грубы ошибки - некоторые города находятся под другими наименованиями. С помощью словаря распределим эти города по нужным названиями

In [41]:
for col in ['region', 'device_type', 'grade']:
    print(df[col].value_counts(dropna=False))

print(df['grade'].value_counts().sort_index())

region
Уфа                843
Краснодар          806
Воронеж            803
Ростов-на-Дону     796
Новосибирск        786
Пермь              763
Екатеринбург       751
Казань             748
Москва             734
Санкт-Петербург    712
г.Казань            39
СПб                 36
казань              34
мск                 31
Санкт Петербург     27
москва              26
спб                 26
г. Москва           20
Moskva              19
Name: count, dtype: int64
device_type
desktop    4752
mobile     2840
tablet      408
Name: count, dtype: int64
grade
6     1173
7     1170
10    1165
11    1146
9     1131
8     1110
5     1105
Name: count, dtype: int64
grade
5     1105
6     1173
7     1170
8     1110
9     1131
10    1165
11    1146
Name: count, dtype: int64

In [42]:
region_map = {
    # Казань
    'г.Казань': 'Казань',
    'казань':   'Казань',
    # Санкт-Петербург
    'СПб':            'Санкт-Петербург',
    'спб':            'Санкт-Петербург',
    'Санкт Петербург':'Санкт-Петербург',
    # Москва
    'мск':      'Москва',
    'москва':   'Москва',
    'г. Москва':'Москва',
    'Moskva':   'Москва',
}

df['region'] = df['region'].replace(region_map)

print(df['region'].value_counts())
assert df['region'].nunique() == 10
assert set(df['region'].unique()) == {
    'Москва','Санкт-Петербург','Казань','Екатеринбург','Новосибирск',
    'Ростов-на-Дону','Краснодар','Воронеж','Пермь','Уфа'
}

region
Уфа                843
Москва             830
Казань             821
Краснодар          806
Воронеж            803
Санкт-Петербург    801
Ростов-на-Дону     796
Новосибирск        786
Пермь              763
Екатеринбург       751
Name: count, dtype: int64

После проведения маппинга, проверим еще раз device_type и grade

In [43]:
print(df['device_type'].value_counts(dropna=False))
print(df['grade'].value_counts().sort_index())

device_type
desktop    4752
mobile     2840
tablet      408
Name: count, dtype: int64
grade
5     1105
6     1173
7     1170
8     1110
9     1131
10    1165
11    1146
Name: count, dtype: int64

Теперь получилось ровно 8000 уникальных учеников

In [45]:
print(df.shape)

(8000, 46)

Посчитаем длительность

In [ ]:
df['end_time'].dtype
df['start_time'] = pd.to_datetime(df['start_time'], errors='coerce')
df['end_time']   = pd.to_datetime(df['end_time'], errors='coerce')
print("Не распарсилось start_time:", df['start_time'].isna().sum())
print("Не распарсилось end_time:  ", df['end_time'].isna().sum())

df['duration_min'] = (df['end_time'] - df['start_time']).dt.total_seconds() / 60

print(df['duration_min'].describe())
print("Отрицательные длительности:", (df['duration_min'] < 0).sum())
print("NaN длительности:", df['duration_min'].isna().sum())

Не распарсилось start_time: 0
Не распарсилось end_time:   0
count    8000.000000
mean       13.997690
std         2.080260
min         0.300000
25%        13.000000
50%        14.133333
75%        15.216667
max        19.566667
Name: duration_min, dtype: float64

Отрицательные длительности: 0
NaN длительности: 0

In [55]:
print(df['school_number'].value_counts().head(15))
print("Всего уникальных школ:", df['school_number'].nunique())

school_number
40    160
34    159
54    157
5     154
22    150
6     150
55    150
12    149
10    149
56    146
39    145
21    145
47    145
30    143
4     142
Name: count, dtype: int64
Всего уникальных школ: 59

In [51]:
fast = df[df['duration_min'] < 3].sort_values('duration_min')
print(f"Сессий < 3 мин: {len(fast)}")
print(fast[['student_id', 'region', 'grade', 'total_score', 
            'duration_min', 'device_type', 'attempts_count', 'disconnects']])

slow = df[df['duration_min'] > 19].sort_values('duration_min')
print(f"Сессий > 19 мин: {len(slow)}")
print(slow[['student_id', 'region', 'grade', 'total_score', 
            'duration_min', 'device_type', 'attempts_count', 'disconnects']])

Сессий < 3 мин: 72
     student_id           region  grade  total_score  duration_min device_type  attempts_count  disconnects
2341    S202329      Новосибирск      5            1      0.300000      mobile               1            0
1158    S201152      Новосибирск      5            5      0.316667     desktop               1            0
2692    S202678            Пермь      5            3      0.316667     desktop               1            0
483     S200482           Казань      6            3      0.333333     desktop               1            0
1449    S201441          Воронеж      5            4      0.333333      mobile               1            0
...         ...              ...    ...          ...           ...         ...             ...          ...
5491    S205466           Москва     10            2      0.483333     desktop               1            0
7945    S207910  Санкт-Петербург      5            3      0.500000     desktop               1            0
7395    S207364     Екатеринбург     10            3      0.500000     desktop               1            0
8001    S207965           Казань      7            2      0.500000     desktop               1            0
6507    S206479      Новосибирск     10            3      0.516667     desktop               1            0

[72 rows x 8 columns]
Сессий > 19 мин: 7
     student_id       region  grade  total_score  duration_min device_type  attempts_count  disconnects
5328    S205304  Новосибирск      5            2     19.033333      tablet               1            0
1749    S201739       Москва      6            9     19.166667      mobile               1            0
1433    S201425       Казань      8            3     19.233333      mobile               2            0
6966    S206937      Воронеж      8            9     19.266667     desktop               2            1
7173    S207143        Пермь      9            7     19.283333      mobile               1            0
6575    S206547  Новосибирск      6            7     19.466667     desktop               1            0
3425    S203405      Воронеж      6            7     19.566667     desktop               2            0

# Визуализация данных

EDA проведен успешно, визуализируем данные и поймем закономерности